### ISSUE TITLE
Windows limitations

### ISSUE THREAD

**Issue by ghost** [seregazhuk/reactphp-book#1]
It may be worth updating so that it is made clear earlier in the book that STDIN/STDOUT and STDERR are blocking on windows machines. This appears to be covered on page 183 however examples of code using STDIN start appearing on page 53.

This could cause a level of frustration when the supplied example codes do not work if not explained.

An example of such an error message is (taken from running a later example):

> `PHP Fatal error:  Uncaught RuntimeException: Unable to set stream resource to non-blocking mode in C:\Users\pete\PhpstormProjects\reactTest\vendor\react\stream\src\ReadableResourceStream.php:56
> Stack trace:
> #0 C:\Users\pete\PhpstormProjects\reactTest\src\client.php(11): React\Stream\ReadableResourceStream->__construct(Resource id #1, Object(React\EventLoop\StreamSelectLoop))
> #1 {main}
>   thrown in C:\Users\pete\PhpstormProjects\reactTest\vendor\react\stream\src\ReadableResourceStream.php on line 56
> 
> Fatal error: Uncaught RuntimeException: Unable to set stream resource to non-blocking mode in C:\Users\pete\PhpstormProjects\reactTest\vendor\react\stream\src\ReadableResourceStream.php:56
> Stack trace:
> #0 C:\Users\pete\PhpstormProjects\reactTest\src\client.php(11): React\Stream\ReadableResourceStream->__construct(Resource id #1, Object(React\EventLoop\StreamSelectLoop))
> #1 {main}
>   thrown in C:\Users\pete\PhpstormProjects\reactTest\vendor\react\stream\src\ReadableResourceStream.php on line 56

An issue raised for this problem was raised in React's Github page (https://github.com/reactphp/stream/issues/117) but as this is an issue with the underlying way Windows works does not appear it will be fixed.

**Comment by seregazhuk** [comment]
Hi @AlexaBible 
Sure, I'll add a notice to the book about this issue!
Thanks 👍

**Comment by seregazhuk** [comment]
Done! I've published a new fixed version of the book!
